# Generated by Django 5.2.7 on 2025-10-18 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literary_archetype', models.CharField(max_length=150, verbose_name='Literary Archetype')),
                ('archetype_traits', models.TextField(verbose_name='Archetype Traits')),
            ],
            options={
                'verbose_name': 'Archetype',
                'verbose_name_plural': 'Archetypes',
                'ordering': ['literary_archetype'],
            },
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Rarity Name')),
                ('level', models.PositiveIntegerField(verbose_name='Rarity Level')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price by Rarity')),
            ],
            options={
                'verbose_name': 'Rarity',
                'verbose_name_plural': 'Rarities',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='CharacterCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Character Name')),
                ('can_participate_in_rotation', models.BooleanField(default=True, verbose_name='Can participate in shop rotations')),
                ('archetype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.archetype', verbose_name='Archetype')),
                ('rarity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rarity', verbose_name='Rarity')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['name'],
            },
        ),
    ]
