# Generated by Django 5.2.7 on 2025-10-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_charactercard_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archetype',
            options={'ordering': ['id'], 'verbose_name': 'Archetype', 'verbose_name_plural': 'Archetypes'},
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='rarity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rarity', verbose_name='Rarity'),
        ),
    ]
