# Generated by Django 5.2.7 on 2025-10-29 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_archetype_options_alter_charactercard_rarity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archetype',
            options={'ordering': ['literary_archetype'], 'verbose_name': 'Archetype', 'verbose_name_plural': 'Archetypes'},
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.rarity', verbose_name='Rarity'),
        ),
        migrations.AlterField(
            model_name='rarity',
            name='level',
            field=models.PositiveIntegerField(help_text='Numeric rarity level used for algorithmic calculations. Lower numbers are more common; higher numbers are rarer.', unique=True, verbose_name='Rarity Level'),
        ),
        migrations.AlterField(
            model_name='rarity',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rarity Name'),
        ),
    ]
