# Generated by Django 5.2.7 on 2025-11-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_archetype_options_alter_charactercard_rarity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charactercard',
            name='legend_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charactercard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
