# Generated by Django 5.2.7 on 2025-11-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_charactercard_legend_id_alter_charactercard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactercard',
            name='legend_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
