# Generated by Django 5.2.7 on 2025-10-29 19:56

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_archetype_options_alter_charactercard_rarity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('rotation_type', models.CharField(max_length=150, verbose_name='Rotation Type')),
            ],
            options={
                'verbose_name': 'Shop Schedule',
                'verbose_name_plural': 'Shop Schedules',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ShopScheduleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Sale Price')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.charactercard', verbose_name='Character')),
                ('shop_scheduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopscheduler', verbose_name='Shop Scheduler')),
            ],
            options={
                'ordering': ['shop_scheduler'],
            },
        ),
    ]
