# Generated by Django 5.2.7 on 2025-10-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopscheduler',
            name='rotation_type',
            field=models.CharField(default='Daily', max_length=150, verbose_name='Rotation Type'),
        ),
        migrations.AlterField(
            model_name='shopscheduler',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
