# Generated by Django 5.2.7 on 2025-11-03 20:48

import django.db.models.deletion
import shop.models
from django.db import migrations, models
from shop.models import end_time_default, start_time_default


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shopscheduler_rotation_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopscheduleitems',
            options={'ordering': ['shop_scheduler'], 'verbose_name': 'Schedule Items', 'verbose_name_plural': 'Schedule Items'},
        ),
        migrations.AlterModelOptions(
            name='shopscheduler',
            options={'ordering': ['start_time'], 'verbose_name': 'Shop Scheduler', 'verbose_name_plural': 'Shop Scheduler'},
        ),
        migrations.AlterField(
            model_name='shopscheduleitems',
            name='shop_scheduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_items', to='shop.shopscheduler', verbose_name='Shop Scheduler'),
        ),
        migrations.AlterField(
            model_name='shopscheduler',
            name='end_time',
            field=models.DateTimeField(default=end_time_default, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='shopscheduler',
            name='start_time',
            field=models.DateTimeField(default=start_time_default, verbose_name='Start Time'),
        ),
    ]
