# Generated by Django 5.2.7 on 2025-11-09 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_archetype_options_alter_charactercard_rarity_and_more'),
        ('shop', '0003_alter_shopscheduleitems_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopscheduleitems',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_characters', to='core.charactercard', verbose_name='Character'),
        ),
    ]
