# Generated by Django 5.2.7 on 2025-11-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_charactercard_legend_id'),
        ('shop', '0004_alter_shopscheduleitems_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopscheduler',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='shop_schedules', through='shop.ShopScheduleItems', through_fields=('shop_scheduler', 'character'), to='core.charactercard'),
        ),
    ]
