# Generated by Django 5.2.7 on 2025-12-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shopscheduler_characters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopscheduler',
            options={'ordering': ['-start_time'], 'verbose_name': 'Shop Scheduler', 'verbose_name_plural': 'Shop Scheduler'},
        ),
    ]
