# Generated by Django 5.2.7 on 2025-12-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_charactercard_legend_id'),
        ('shop', '0006_alter_shopscheduler_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shopscheduler',
            constraint=models.UniqueConstraint(fields=('start_time',), name='unique_shop_per_start_time'),
        ),
    ]
