# Generated by Django 5.2.7 on 2025-11-30 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_charactercard_legend_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usercards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_id', models.CharField(max_length=300, verbose_name='Stripe Payment Reference')),
                ('order_reference', models.CharField(max_length=300, verbose_name='Order Reference Number')),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.charactercard', verbose_name='Character Purchased')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
            ],
            options={
                'verbose_name': 'Usercards',
                'verbose_name_plural': 'Usercards',
            },
        ),
    ]
