# Generated by Django 5.2.7 on 2025-12-01 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binder', '0001_initial'),
        ('core', '0006_alter_charactercard_legend_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usercards',
            constraint=models.UniqueConstraint(fields=('owner', 'character'), name='unique_owner_character_pair'),
        ),
    ]
