# Generated by Django 5.2.7 on 2025-12-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binder', '0002_usercards_unique_owner_character_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercards',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Purchase Price'),
        ),
    ]
