# Generated by Django 5.2.7 on 2026-01-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binder', '0003_alter_usercards_purchase_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercards',
            options={'ordering': ['-date_purchased'], 'verbose_name': 'Usercards', 'verbose_name_plural': 'Usercards'},
        ),
    ]
